### ISSUE TITLE
Keeping track of values

### ISSUE THREAD

**Issue by tf79** [Mri-monitoring/Mri-app#5]
Over the weekend I trained >10k nets with different parameters. Now I have to go through all plots and find the best ones. 
It would be nice to do some evaluation on them in Matlab, or what ever. Therefor storing all values from plots in a file would be nice. Maybe specifying the path to store them and defining the separator in the config file. Format could be .csv 
This would make it possible to make some evaluation on the impact of different hyperparameter.

**Comment by nharada1** [comment]
I'm torn on this because I'd like most of the tracking and metrics to eventually end up in the web-app. For now though, I've added a line to the logging that shows maxes and mins after training concludes. Something like:

```
'Integration Test' Final Extremes: ['Accuracy (Max: 0.9789 Min: 0.1086)', 'Loss (Max: 2.38385 Min: 0.0652028)']
```

So once you train, just look through your log for "Final Extremes". Something like 

```
grep "Final Extremes" ../mri.log
```

should be enough.

**Comment by nharada1** [comment]
This is a little ad-hoc for now but in the future I'll have a better solution.

**Comment by haoyangz** [comment]
I also prefer to analyze the results using scripts instead of naked-eye. Current solution works fine for me, but I will have to turn on the `debug=True` to be able to see it. This generates hundreds of megabytes of log when I am trying dozens of hyper-params. So I would appreciate it if the _Final Extremes_ can be print even in `debug=False` mode, as these final extremes are not really for debug but rather essential.

**Comment by nharada1** [comment]
I've changed the default logging level from WARNING to INFO, which should show a more complete view without showing all that Caffe output. In the future (note to myself) the logging level should be adjustable. 

Commit ac9b57a5a4d7e43119e2774e51442a7bf36f4842
